### ISSUE TITLE
Missing placeholder in log string

### ISSUE THREAD

**Issue by judy2k** [Nexmo/comms-router#88]
3 parameters are passed to `Logger.error`, but there are only 2 `{}` placeholders in the format string.

https://github.com/Nexmo/comms-router/blob/01a0a6635b371c865fb1e15f9cde1277f6e2982b/core/src/main/java/com/softavail/commsrouter/app/QueueProcessor.java#L126

**Comment by ikrustev** [comment]
@judy2k:

Log4j2 mirrors SLF4J special handling of throwable when it is passed after the last parameter matching a placeholder. This handling by default this outputs the stack trace of the passed throwable.

So this construct here and elsewhere is intentional.

The passing the exception twice is also intentional. For the first one we have placeholder, so the logger will log the result of e.toString() as part of the log line. For the second one there is no placeholder, which make the logger log the stack trace.

This way we have the exception description on the ERROR line logging it and also have the stack trace.
